# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  erc:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:1.8.3

    steps:
    - uses: actions/checkout@v4

    - name: Run ERC
      run: kibot -d generated -s drc -i

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_Output
        path: generated

  drc:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:1.8.3
    needs: erc

    steps:
    - uses: actions/checkout@v4

    - name: Run DRC
      run: kibot -d generated -s erc -i

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_Output
        path: generated

  fab:
    name: generate fabrication files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:1.8.3
    needs: drc

    steps:
    - uses: actions/checkout@v4

    - name: Run fabrication generation
      run: kibot -d generated fab assembly doc

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: generated/*
